/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent_day_1

import java.io.File

class FatSanta {

    private fun elfsSnacks() = File("input/fatties.txt")
        .readText()
        .split("\n\n")
        .asSequence()
        .mapIndexed { index, s ->
            index to s
                .split("\n")
                .mapNotNull { it.toIntOrNull() }
                .sum()
        }

    fun findTopFatties(top: Int) = elfsSnacks()
        .sortedByDescending { it.second }
        .take(top)
}

fun main() {
    println(
        FatSanta()
            .findTopFatties(3)
            .sumOf { it.second }
    )
}
